version: '2'

services:
  api:
    build: .
    links:
      - redis
    volumes:
      - data:/mnt/data
    environment:
      - DISK_PATH=/mnt/data/file.txt
      - REDIS_URL=redis://redis:6379
    ports:
     - 8080:8080

  redis:
    image: redis:3.2-alpine

volumes:
 data: