version: '2'

services:
  api:
    build: .
    links:
      - redis
      - postgres
      - peer
    volumes:
      - data:/mnt/data
    environment:
      - DISK_PATH=/mnt/data/file.txt
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgres://postgres:laika@postgres:5432/postgres
      - LAIKA_PEER_TEST=http://peer:8080/
    ports:
     - 8080

  peer:
    build: .
    environment:
      - MESSAGE=nested peer
  redis:
    image: redis:3.2-alpine
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=laika
  test:
    build: .
    links:
      - api
    environment:
      - LAIKA_URL=http://api:8080
      - DISK_PATH=true
      - REDIS_URL=true
      - POSTGRES_URL=true
      - LAIKA_PEERS=test
    entrypoint: npm test

volumes:
 data: